# Template: Creates a REST API gateway integrated w/ a lambda function using inline code.

# CLI CALL - aws cloudformation create-stack --stack-name <StackName> --template-body file://<FileName> --capabilities CAPABILITY_IAM
# In some cases, must explicitly acknowledge that your stack template contains certain capabilities 
AWSTemplateFormatVersion: '2010-09-09'
Description: A CF template that creates an API Gateway with a single resource integrated with a Lambda function backend.

Resources:
  # Public facing REST API Gateway.
  ApiGatewayRest:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Test API integration w/ Lambda.
      EndpointConfiguration: 
        Types: 
          - REGIONAL
      Name: TestCFApi

  # Resource for the REST API Gateway.  Defines a path for a URL.  In this case, /random path is created.
  ResourceApiGatewayRandom:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt
        - ApiGatewayRest
        - RootResourceId
      PathPart: random
      RestApiId: !Ref ApiGatewayRest

  # Method - GET.  Adds the GET method options to the /random resource path.  Integrated with the Random Lambda function.
  MethodApiGatewayRandom:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:  
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Credentials: !GetAtt RoleApiGateway.Arn
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaRandom.Arn}/invocations'
      ResourceId: !Ref ResourceApiGatewayRandom
      RestApiId: !Ref ApiGatewayRest

  # Deploys the REST API to a stage so that clients can call the API over the internet.  The stage acts as an environment.
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: MethodApiGatewayRandom
    Properties:
      Description: Lambda API Deployment
      RestApiId: !Ref ApiGatewayRest

  # Creates the Stage that the API gateway gets deployed to.
  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ApiGatewayDeployment
      Description: Lambda API Stage v0
      RestApiId: !Ref ApiGatewayRest
      StageName: 'Dev'

  # Role that gives API gateway access to all operations for the Random Lambda.
  RoleApiGateway:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: [apigateway.amazonaws.com]
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: LambdaAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'lambda:*'
                Resource: !GetAtt LambdaRandom.Arn
      RoleName: ApiGatewayLambdaExecutionRole

  # Role for Lambda to allow it to publish logs.
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: LambdaPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: '*' 
      RoleName: LambdaRole 
    
  # Lambda function (Random) that returns a random number 1-10.
  LambdaRandom:
    Type: AWS::Lambda::Function
    Properties:
      Description: Test Lambda function integrated w/ API.
      FunctionName: RandomLambda
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs12.x
      Code:
        ZipFile:  |
          console.log('Loading function');

          exports.handler = async (event) => {
              let min = 0;
              let max = 10;
              let responseCode = 200;
              
              let generatedNumber = Math.floor(Math.random() * max) + min;
              
              let responseBody = {
                  message: generatedNumber,
                  input: event
              }
              
              let response = {
                  statusCode: responseCode,
                  headers: {
                      "x-custom-header" : "my custom header value"
                  },
                  body: responseBody.message
              }
              
              console.log("Entire event: " + JSON.stringify(event));
              console.log("Event body: " + JSON.stringify(event.body));
              console.log("Random number generated: ", responseBody.message);
              return response;
              
          };

  # Lambda permission that grants API Gateway the ability to invoke the function at a specific path.        
  PermissionLambdaRandom:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Ref LambdaRandom
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: ApiGatewayRest
          - "/*/GET/random"
